### PR TITLE
Remove support for tasks in PCF<1.9

### PR DESCRIPTION
**Pull request by ericbottard**
Refactor config to allow easy creation of a Version probing bean

Fixes https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/issues/169

### CODE REVIEW

**Comment by trisberg** [comment]
Tests fail if I run against an older CF installation like PCF 1.8, is that what we want? I would expect task tests to be disabled in this environment.

```
Tests run: 7, Failures: 0, Errors: 5, Skipped: 1, Time elapsed: 6.297 sec <<< FAILURE!
testReLaunch(org.springframework.cloud.deployer.spi.cloudfoundry.CloudFoundryTaskLauncherIntegrationTests)  Time elapsed: 0.505 sec  <<< ERROR!
java.lang.UnsupportedOperationException: Cloud Foundry API version 2.58.0 is earlier than 2.63.0 and is incompatible with cf-java-client 2.6.0.RELEASE. It is thus unsupported
	at org.springframework.cloud.deployer.spi.cloudfoundry.UnsupportedVersionTaskLauncher.failure(UnsupportedVersionTaskLauncher.java:81)
	at org.springframework.cloud.deployer.spi.cloudfoundry.UnsupportedVersionTaskLauncher.launch(UnsupportedVersionTaskLauncher.java:50)
...
```

**Comment by ilayaperumalg** [comment]
@trisberg I think we should rebase this PR and see if this [commit](https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/commit/dca78851b9f6e3e759e8e596a341bc881434e2e6) fixes the above issue.

**Comment by ilayaperumalg** [comment]
If it does, then I don't think we need #179

**Comment by trisberg** [comment]
Agree, testing now

**Comment by trisberg** [comment]
LGTM now, merging

**Comment by trisberg** [comment]
Rebased and merged as commit d6ee4ee1b7e51ab1157915984a80015849ff6757

**Pull request closed without merging**
