### PR TITLE
Add support for passing JAVA_OPTS option

### LINKED ISSUE #242: Add support to amend JAVA_OPTS for stream/task deployments
As a user, I'd like to have global stream and task level properties to supply JAVA_OPTS configs, so I can influence all the stream and task deployments to include the overridden configs at runtime.

Note: For the Task apps, we have the ability to supply arguments, but they are simply command-line-args. It'd be nice to override JAVA_OPTS similar to how [Local-deployer](https://github.com/spring-cloud/spring-cloud-deployer-local/blob/master/spring-cloud-deployer-local/src/main/java/org/springframework/cloud/deployer/spi/local/LocalDeployerProperties.java#L182) supports it today.

See this [SO thread](https://stackoverflow.com/questions/49639086/setting-java-timezone-for-all-tasks-deployed-to-pcf-using-spring-cloud-dataflow) for background. There have been requirements to supply APM agent configs via JAVA_OPTS to all the deployed apps, too.

### PR DESCRIPTION
**Pull request by ilayaperumalg**
- Add `javaOpts` as the CloudFoundry Deployment properties
   - the same property can be set via Deployment Request as well
 - Set JAVA_OPTS environment variable if it is set

Resolves #242

### CODE REVIEW

**Comment by sabbyanandan** [comment]
I tried the following Task launch in SCDF and the JAVA_OPTS gets set correctly! 

```
dataflow:>task list
╔═════════╤═══════════════╤═══════════╗
║Task Name│Task Definition│Task Status║
╠═════════╪═══════════════╪═══════════╣
║done     │timestamp      │unknown    ║
╚═════════╧═══════════════╧═══════════╝

dataflow:>task launch --name done --properties "deployer.*.javaOpts=-Duser.timezone=Australia/Sydney"
```

logs: _(note: at the time of this execution, Time in Australia: `12:34 AM` (Saturday); SF: `7:34 AM` (Friday))_
```
   2018-04-06T07:34:00.02-0700 [APP/TASK/done/0] OUT 2018-04-07 00:34:00.029  INFO 7 --- [           main] TimestampTaskConfiguration$TimestampTask : 2018-04-07 00:34:00.029
```

**Comment by lframirez89** [comment]
Hi Sabby,

I tested the PR but am not able to get it to work. This is what I did:
1. Checked out master of spring-cloud-dataflow-server-cloudfoundry (1.5.0.BUILD-SNAPSHOT) and built.
2. Checked out PR/243 of spring-cloud-deployer-cloudfoundry, (I verified the changes to the 3 files) and built. 
3. Manually replaced the spring-cloud-deployer-cloudfoundry-1.4.0.BUILD-SNAPSHOT.jar artifact inside the spring-cloud-dataflow-server-cloudfoundry-1.5.0.BUILD-SNAPSHOT.jar artifact with the one generated by the PR. 
4. I deployed and started dataflow in PCF. 
5. I executed my job exactly as you showed in your example: task launch --name my_job --properties "deployer.*.javaOpts=-Duser.timezone=America/New_York", but it still ran in UTC time. 
6. I also did the test to define it globally by defining a parameter in the DF 'User Provided Env Variables' section. I added SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_JAVAOPTS        '-Duser.timezone=America/New_York'. I also tried ...JAVA_OPTS but the task still ran in UTC.

Is there something I'm doing wrong? Also, what is the proper way to define the JAVA_OPTS globally and individually for each task? Individually I mean, such as defining it somewhere in the task definition, and globally, what would be the correct syntax for defining in DF?

Thanks

**Comment by ilayaperumalg** [comment]
@lframirez89  Thank you for trying out the PR. I made a mistake by not pushing the change for the task launcher. Sorry about that. I have just updated the PR with the changes required. Let us know if you can give this PR branch a try again.

**Comment by lframirez89** [comment]
Hi @sabbyanandan & @ilayaperumalg, I re-did the test following your steps. I realized I wasn't seeing the changes of the 4 files even after I had pulled from the PR this morning. So I manually copied & pasted the 4 files into the deployer project and built/installed to my local m2. 

1. Built deployer from PR, and installed in local repo.
2. Built/installed DF and made sure it pulled deployer artifact from local repo.
3. Opened the generated DF artifact, -> Libs -> opened deployer artifact, and validated the PR changes were there.
4. Deleted the old DF App from PCF, and pushed the new one. 
5. Launched task by using: task launch --name mytask --properties "deployer.*.javaOpts=-Duser.timezone=America/New_York" but it ran in UTC. I also tried instead of * with actual task name but still the same.
6. Applied global setting to DF User provided Env Vars as: SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_JAVA_OPTS     ->       '-Duser.timezone=America/New_York'       (with and without single quotes), but still ran in UTC.

I can't think of anything else I may be missing. As I mentioned, I did open the DF jar once generated, and then opened the deployer jar inside libs, and verified the changes were there. What else could it be? Thank you for your help.

**Comment by ilayaperumalg** [comment]
Hi @lframirez89 ,

It looks like the way you pass the property is incorrect. We need to pass it with `cloudfoundry` prefix:

```
task launch --name mytask --properties "deployer.*.cloudfoundry.javaOpts=-Duser.timezone=America/New_York
```

**Comment by lframirez89** [comment]
Hi @ilayaperumalg 

I was able to get it to work for a single task by adding the 'cloudfoundry' from your last comment. I am able to apply the timezone using the following two variations:

1. task launch --name mytask --properties "deployer.*.cloudfoundry.javaOpts=-Duser.timezone=America/New_York"
2. task launch --name mytask --properties "deployer.mytask.cloudfoundry.javaOpts=-Duser.timezone=America/New_York"

However, I am not able to get it to work for the global setting in the DataFlow User Provided Env Vars. I've tried the following variations:

1. SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_JAVA_OPTS  -->  -Duser.timezone=America/New_York
2. SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_JAVAOPTS  -->  -Duser.timezone=America/New_York
3. spring.cloud.deployer.cloudfoundry.javaOpts --> -Duser.timezone=America/New_York
4. SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_JAVA_OPTS  -->  '-Duser.timezone=America/New_York'
5. SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_JAVAOPTS  -->  '-Duser.timezone=America/New_York'
6. spring.cloud.deployer.cloudfoundry.javaOpts --> '-Duser.timezone=America/New_York'

I even tried percent encoding the '=' and the '/' in the timezone string, but still I have not been able to get the global setting to work. Can you please provide the exact syntax for defining this globally in the SCDF User Provided Environment Variables section? Thank you.

**Comment by markpollack** [comment]
There are global properties that can be set for streams and tasks.  See https://docs.spring.io/spring-cloud-dataflow-server-cloudfoundry/docs/1.4.0.RELEASE/reference/htmlsingle/#configuration-app-defaults

So for example, 

```
cf set-env dataflow-server SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_MEMORY 512
```
or in this case

```
cf set-env dataflow-server SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_JAVAOPTS -Duser.timezone=America/New_York
```

use ` SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_TASK_XYZ` to set the deployer property `XYZ` for tasks globally.

**Comment by markpollack** [comment]
squashed and merged as 978d750c66a8f65a812c9df68e705fbaea1a916e

**Comment by ilayaperumalg** [comment]
I think the global stream level property needs to be: `SPRING_CLOUD_DEPLOYER_CLOUDFOUNDRY_STREAM_JAVA_OPTS` 

The difference is: JAVAOPTS -> JAVA_OPTS

**Pull request closed without merging**
