### PR TITLE
Add TestRule for task launcher incompatibility

### LINKED ISSUE #179: Add junit TestRule for checking task launcher compatibility against PCF versions

### PR DESCRIPTION
**Pull request by ilayaperumalg**
Resolves #179

### CODE REVIEW

**Comment by trisberg** [comment]
I think we need a separate Rule that isn't based on AbstractExternalResourceTestSupport since that will cause the build to fail if we set EXTERNAL_SERVERS_REQUIRED=true which is done on the CI. We need a Rule that just checks the version and ignores the task tests if it isn't supported.

**Comment by ilayaperumalg** [comment]
@trisberg Isn't [this](https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/commit/dca78851b9f6e3e759e8e596a341bc881434e2e6) sufficient already?

**Comment by trisberg** [comment]
I just saw that commit, yes, that looks like it will do it

**Comment by trisberg** [comment]
Already addressed in https://github.com/spring-cloud/spring-cloud-deployer-cloudfoundry/commit/dca78851b9f6e3e759e8e596a341bc881434e2e6

**Pull request closed without merging**
